name: Forge Test & Coverage

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version

      - name: Run Forge fmt
        run: forge fmt --check
        id: fmt
        working-directory: solidity

      - name: Run Forge build
        run: forge build --sizes
        id: build
        working-directory: solidity

      - name: Run Forge tests
        run: forge test -vvv
        id: test
        working-directory: solidity

      - name: Run Forge coverage
        run: forge coverage --no-match-coverage "(script|test)" --report lcov
        id: coverage
        working-directory: solidity

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: solidity/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
